### ISSUE TITLE
Index Array Length Issue

### ISSUE THREAD

**Issue by sriram7777** [liurui39660/MIDAS.Python#1]
Why should index array used in Filtering Core be of length row * col? Shouldn't it be just row? 
https://github.com/liurui39660/MIDAS.Python/blob/a72af8da36e9eff52d660f8e45c417c2e14f637e/src/MIDAS/FilteringCore.py#L17

The same implementation in C++ agrees with this I suppose.
https://github.com/Stream-AD/MIDAS/blob/149509a90a0fb35fd68f7485a0ab0e661d74644b/src/FilteringCore.hpp#L42

**Comment by liurui39660** [comment]
I guess you are right. I'll check it later. Thanks for pointing it out.

**Comment by sriram7777** [comment]
Perfect. I was thinking of giving the PR. Thanks for the quick response
